package com.kni.platform.security.cert

import android.content.Context
import android.util.Log
import com.kni.platform.security.NativeTlsEngine
import java.io.ByteArrayInputStream
import java.io.File
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate

/**
 * Materializes the real Root CA generated by the native `tls-core` engine into a
 * `.pem` file the user can install or export. Replaces the previous placeholder.
 */
class CertificateManager(private val context: Context) {
    private val caFileName = "kni_root_ca.pem"
    private fun caDir(): String = File(context.filesDir, "ca").absolutePath

    /** Returns the CA certificate file, (re)writing it from the native CA. */
    fun getCertificateFile(): File? {
        val file = File(context.filesDir, caFileName)
        val engine = NativeTlsEngine.create(caDir())
        if (engine == null) {
            Log.e(TAG, "Native TLS engine init failed")
            return if (file.exists()) file else null
        }
        return try {
            val pem = engine.caCertPem()
            if (pem.isEmpty()) {
                Log.e(TAG, "Native CA returned empty PEM")
                if (file.exists()) file else null
            } else {
                file.writeBytes(pem)
                file
            }
        } finally {
            engine.destroy()
        }
    }

    /** The CA parsed as an X.509 certificate (DER-encodable for KeyChain install). */
    fun getX509(): X509Certificate? {
        val file = getCertificateFile() ?: return null
        return try {
            val cf = CertificateFactory.getInstance("X.509")
            cf.generateCertificate(ByteArrayInputStream(file.readBytes())) as X509Certificate
        } catch (e: Exception) {
            Log.e(TAG, "Failed to parse CA certificate", e)
            null
        }
    }

    companion object {
        private const val TAG = "CertificateManager"
    }
}
